# Generated by Django 4.2.25 on 2025-10-19 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_variant_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='short_name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='VariantPresetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='EMPTY', max_length=6)),
                ('collection_time', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], default='EMPTY', max_length=5)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.variantpreset')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='VariantCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_completions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.variant')),
            ],
            options={
                'unique_together': {('user', 'variant')},
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_variants', through='api.VariantCompletion', to=settings.AUTH_USER_MODEL),
        ),
    ]
