# Generated by Django 4.2.25 on 2025-10-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_variantpreset_rename_short_name_device_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='accessory',
            field=models.CharField(choices=[('NONE', 'None'), ('GLASSES', 'Glasses'), ('HAT', 'Hat'), ('MASK', 'Mask'), ('GLASSES_HAT', 'Glasses Hat'), ('GLASSES_MASK', 'Glasses Mask'), ('HAT_MASK', 'Hat Mask'), ('GLASSES_HAT_MASK', 'Glasses Hat Mask'), ('ETC', 'Etc')], default='EMPTY', max_length=20),
        ),
        migrations.AddField(
            model_name='variantpresetitem',
            name='accessory',
            field=models.CharField(choices=[('NONE', 'None'), ('GLASSES', 'Glasses'), ('HAT', 'Hat'), ('MASK', 'Mask'), ('GLASSES_HAT', 'Glasses Hat'), ('GLASSES_MASK', 'Glasses Mask'), ('HAT_MASK', 'Hat Mask'), ('GLASSES_HAT_MASK', 'Glasses Hat Mask'), ('ETC', 'Etc')], default='EMPTY', max_length=20),
        ),
        migrations.AlterField(
            model_name='variant',
            name='target_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.device'),
        ),
    ]
