# Generated by Django 4.2.25 on 2025-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variant_accessory_variantpresetitem_accessory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_suffix',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
