# Generated by Django 4.2.25 on 2025-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_unique_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='english_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
